"""add updated_at to subjects

Revision ID: 1db16ff393aa
Revises: c1d34985beb4
Create Date: 2026-09-22 09:50:44.680056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1db16ff393aa'
down_revision: Union[str, Sequence[str], None] = 'c1d34985beb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subjects', 'updated_at')
    # ### end Alembic commands ###
