"""add cycles and study sessions

Revision ID: 9d2da67f433e
Revises: 8804832e8807
Create Date: 2026-09-24 09:40:42.481866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d2da67f433e'
down_revision: Union[str, Sequence[str], None] = '8804832e8807'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subjects', 'completed_hours')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('completed_hours', sa.FLOAT(), nullable=False))
    # ### end Alembic commands ###
